// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slide canvas aspect ratio.
 *
 * One of `16:9` (default) or `4:3`. Drives the logical width/height of
 * every slide and the presenter view's proportions. Wire form on
 * `manifest.json` is the label string; internal pixel dimensions are looked
 * up via [`AspectRatio::width`] / [`AspectRatio::height`].
 */
export type AspectRatio = "16:9" | "4:3";
