// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManifestSection = { name: string, startIndex: number, endIndex: number, plannedDurationMs: number, };
