// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestSlide } from "./ManifestSlide";

export type Manifest = { version: number, peithoVersion: string, title: string, slideCount: number, slides: Array<ManifestSlide>, };
