// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestSlideText } from "./ManifestSlideText";

export type ManifestSlide = { index: number, key: string, src: string, hasNotes: boolean, text: ManifestSlideText, };
