// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestImage } from "./ManifestImage";
import type { ManifestSection } from "./ManifestSection";
import type { ManifestSlide } from "./ManifestSlide";

export type Manifest = { version: number, peithoVersion: string, title: string, slideCount: number, plannedDurationMs: number | null, sections: Array<ManifestSection>, slides: Array<ManifestSlide>, images: Array<ManifestImage>, };
