// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeasuredRun = { text: string, color: string, fontFamily: string, fontSizePx: number, bold: boolean, italic: boolean, underline: boolean, breakBefore: boolean, };
