// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasuredRect } from "./MeasuredRect";

export type MeasuredImage = { src: string, alt: string, rect: MeasuredRect, };
