// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasuredBoxStyle } from "./MeasuredBoxStyle";
import type { MeasuredParagraph } from "./MeasuredParagraph";
import type { MeasuredRect } from "./MeasuredRect";

export type MeasuredBox = { slot: string, rect: MeasuredRect, style: MeasuredBoxStyle, paragraphs: Array<MeasuredParagraph>, };
