// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeasuredBoxStyle = { backgroundColor: string, borderColor: string, borderWidth: number, borderRadius: number, };
