// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasuredRun } from "./MeasuredRun";

export type MeasuredParagraph = { align: string, bulletLevel: number | null, numbered: boolean, bulletContinuation: boolean, runs: Array<MeasuredRun>, };
