// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasuredSlide } from "./MeasuredSlide";

export type MeasuredDeck = { canvasWidth: number, canvasHeight: number, slides: Array<MeasuredSlide>, };
