// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasuredBox } from "./MeasuredBox";
import type { MeasuredImage } from "./MeasuredImage";

export type MeasuredSlide = { key: string, backgroundColor: string, boxes: Array<MeasuredBox>, images: Array<MeasuredImage>, };
