// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RehearsalSection } from "./RehearsalSection";
import type { RehearsalSlideEntry } from "./RehearsalSlideEntry";

export type RehearsalRecordV2 = { version: 2, recordedAtMs: number, elapsedMs: number, sections: Array<RehearsalSection>, timeline: Array<RehearsalSlideEntry>, };
