// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RehearsalRecordV1 } from "./RehearsalRecordV1";
import type { RehearsalRecordV2 } from "./RehearsalRecordV2";

export type RehearsalRecord = RehearsalRecordV1 | RehearsalRecordV2;
