// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RehearsalSection } from "./RehearsalSection";

export type RehearsalRecordV1 = { version: 1, recordedAtMs: number, elapsedMs: number, sections: Array<RehearsalSection>, };
