// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RehearsalRecord } from "./RehearsalRecord";

export type RehearsalBaseline = { version: number, lastRun: RehearsalRecord | null, };
