// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preview-cache body sources for every surviving parsed slide.
 *
 * Each slide key appears in exactly one of `sources` or `unavailable`. Draft
 * slides are absent because parsing removes them, while skipped slides remain.
 * This map is computed on every build but written only to the preview cache.
 */
export type SlideSources = { version: number, sources: Record<string, string>, unavailable: Record<string, string>, };
