// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncTimerSnapshot } from "./SyncTimerSnapshot";

export type SyncResponse = { seq: number, message: unknown, index: number | null, step: number | null, swapped: boolean, generation: number, session: string, timer: SyncTimerSnapshot | null, nowMs: number, buildError: string | null, };
